#ifndef WRAPHTMLHANDLEINDEX_H
#define WRAPHTMLHANDLEINDEX_H

#include <Arduino.h>

String wrapHtmlhandleIndex(const String& title, const String& body) {
  return "<!DOCTYPE html>"
         "<html lang='id'>"
         "<head>"
         "<meta charset='UTF-8'>"
         "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
         "<title>" + title + "</title>"
         "<style>"
         "/* Reset & dasar */"
         "* { box-sizing: border-box; margin: 0; padding: 0; }"
         "body { background: linear-gradient(135deg, #1a1a1a, #2a2a2a); color: #e0e0e0; font-family: 'Roboto', sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; padding: 20px; }"
         ".container { background: #1e1e1e; padding: 40px; border-radius: 20px; box-shadow: 0 4px 18px rgba(0,0,0,0.4); max-width: 600px; width: 100%; margin: auto; border-top: 8px solid #4CAF50; transition: transform 0.3s ease-in-out; }"
         ".container:hover { transform: scale(1.02); }"
         ".info-header { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 20px; margin-top: 0px; }"
         ".info-item { flex: 1; display: flex; flex-direction: column; align-items: center; margin-top: 0px; }"
         ".info-label { font-size: 14px; color: #aaa; margin-bottom: 5px; }"
         ".info-box { background: #2e2e2e; padding: 8px 12px; border-radius: 10px; width: 100%; text-align: center; font-size: 16px; font-weight: bold; }"
         "@media (max-width: 600px) { .info-header { flex-direction: column; gap: 10px; } }"
         "h2 { color: #4CAF50; margin-top: 50px; margin-bottom: 30px; font-size: 24px; text-align: center; }"
         "form { display: flex; flex-direction: column; align-items: center; gap: 20px; margin-bottom: 30px; }"
         "input[type='file'] { display: none; }"
         ".custom-file-upload { display: block; width: 55%; padding: 12px 24px; border: 1px solid #4CAF50; border-radius: 25px; background-color: rgba(255,255,255,0.05); color: #e0e0e0; font-size: 16px; text-align: center; cursor: pointer; transition: background-color 0.3s ease, color 0.3s ease; margin: 0 auto; }"
         ".custom-file-upload:hover { background-color: #4CAF50; color: #121212; }"
         "input[type='submit'] { display: block; width: 55%; padding: 12px; border: 1px solid #4CAF50; border-radius: 25px; background-color: rgba(255,255,255,0.05); color: #e0e0e0; font-size: 16px; cursor: pointer; transition: background-color 0.3s ease, color 0.3s ease; margin: 0 auto; }"
         "input[type='submit']:hover { background-color: #4CAF50; color: #121212; }"
         ".file-info { text-align: center; font-size: 14px; color: #aaa; }"
         ".file-info span { display: block; margin-top: 5px; }"
         ".links { display: flex; justify-content: space-around; margin-top: 20px; }"
         ".links a { text-decoration: none; color: #4CAF50; font-size: 16px; transition: color 0.3s ease; }"
         ".links a:hover { color: #66BB6A; }"
         "@media (max-width: 600px) { .container { padding: 20px; } h2 { font-size: 18px; } input[type='submit'] { width: 100%; } .links { flex-direction: column; gap: 10px; } }"
         "</style>"
         "<script>"
         "document.addEventListener('DOMContentLoaded', function() {"
         "  const fileInput = document.querySelector('input[type=file]');"
         "  const fileInfo = document.querySelector('.file-info');"
         "  fileInput.addEventListener('change', function() {"
         "    const files = fileInput.files;"
         "    let fileNames = '';"
         "    for (let i = 0; i < files.length; i++) {"
         "      fileNames += files[i].name + '<br>';"
         "    }"
         "    fileInfo.innerHTML = 'Selected files (' + files.length + '):<br>' + fileNames;"
         "  });"
         "});"
         "</script>"
         "</head>"
         "<body>"
         "<div class='container'>" + body + "</div>"
         "</body>"
         "</html>";
}

#endif // WRAPHTMLHANDLEINDEX_H