String wrapHtmlhandleInfo(const String& title, const String& body) {
    return "<!DOCTYPE html>"
           "<html lang='id'>"
           "<head>"
           "<meta charset='UTF-8'>"
           "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
           "<title>" + title + "</title>"
           "<style>"
           "/* Reset & dasar */"
           "* { box-sizing: border-box; margin: 0; padding: 0; }"
           "body { background: linear-gradient(135deg, #1a1a1a, #2a2a2a); font-family: 'Roboto', sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; }"
           ".container { background: #1e1e1e; border-radius: 20px; box-shadow: 0 4px 18px rgba(0, 0, 0, 0.4); max-width: 600px; width: 100%; padding: 30px; border-top: 8px solid #4CAF50; transition: transform 0.3s ease; }"
           ".container:hover { transform: scale(1.02); }"
           "h1 { color: #4CAF50; margin-bottom: 20px; font-size: 24px; text-align: center; }"
           ".info-container { display: flex; flex-wrap: wrap; justify-content: center; align-items: center; gap: 20px; }"
           ".circular-progress { position: relative; width: 180px; height: 180px; }"
           ".circular-progress svg { width: 100%; height: 100%; transform: rotate(-90deg); }"
           ".circular-progress circle { fill: none; stroke-width: 20; stroke-linecap: round; }"
           ".circular-progress .free { stroke: #FFEB3B; transition: stroke-dasharray 0.5s, stroke-dashoffset 0.5s; }"
           ".circular-progress .used { stroke: #2196F3; transition: stroke-dasharray 0.5s; }"
           ".circular-progress .text { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center; color: #e0e0e0; }"
           ".circular-progress .text div { font-size: 18px; font-weight: 500; }"
           ".info-details { display: flex; flex-direction: column; gap: 10px; min-width: 200px; }"
           ".info { display: flex; justify-content: space-between; align-items: center; font-size: 16px; padding: 8px 12px; background: rgba(255, 255, 255, 0.05); border-radius: 6px; }"
           ".info span:first-child { flex: 1; color: #aaa; }"
           ".info .value { font-weight: bold; color: #e0e0e0; display: flex; align-items: center; gap: 8px; }"
           ".legend-box { width: 12px; height: 12px; border-radius: 3px; }"
           ".legend-box.used-box { background-color: #2196F3; }"
           ".legend-box.free-box { background-color: #FFEB3B; }"
           ".back-btn { display: inline-block; text-align: left; margin-top: 20px; text-decoration: none; color: #4CAF50; font-size: 16px; transition: color 0.3s ease; }"
           ".back-btn:hover { color: #66BB6A; }"
           "@media (max-width: 600px) { .info-container { flex-direction: column; } .container { padding: 20px; } h1 { font-size: 20px; } .info { font-size: 14px; } }"
           "</style>"
           "</head>"
           "<body>"
           "<div class='container'>"
           "<h1>" + title + "</h1>"
           "<div class='info-container'>" + body + "</div>"
           "<a href='/' class='back-btn'>Kembali</a>"
           "</div>"
           "</body>"
           "</html>";
  }